### ISSUE TITLE
socket.io-client: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by helloncanella** [invisibleroads/socketIO-client#101]
I'm trying to adapt a [socket.io tutorial's example](http://socket.io/docs/#using-with-express-3/4) to my code, using the npm package [`socket.io-client`](https://www.npmjs.com/package/socket.io-client).

After this attempt I've obtained the error: 

>Failed to load resource: the server http://localhost:3000/socket.io/?EIO=3&transport=polling&t=1451092774034-0 responded with a status of 404 (Not Found)

Bellow the code:

the client 
----------

_exactly as prescribed by the package developer_

    var socket = require('socket.io-client')('http://localhost:3000');
    
    socket.on('news', function(data) {
      console.log(data);
      socket.emit('my other event', {
        my: 'data'
      });
    });

the server
------------

    var express = require('express');
    var app = express();
    
    var server = require('http').Server(app);
    
    var io = require('socket.io')(server);
    
    app.use(express.static(__dirname+'/app'));
    
    app.get('/', function(req,res){
      res.sendFile('index.html');
    });
    
    io.on('connection', function (socket) {
      socket.emit('news', { hello: 'world' });
      socket.on('my other event', function (data) {
        console.log(data);
      });
    });
    
    
    server.listen(process.env.PORT || 3000);

I suppose the problems is related with the line `app.use(express.static(__dirname+'/app'))` . However, I don't know how to use this suspection to workaround the problem.

I appreciate any help.

**Comment by helloncanella** [comment]
Problem solved. The related problem has to do with some conflicts with browsersync, as reported in [this github's issue](https://github.com/BrowserSync/browser-sync/issues/223)

**Comment by invisibleroads** [comment]
Thanks for updating us on the cause of the issue. This will help other users.

**Comment by gregartisi** [comment]
hello, thanks for this post. I have the same problem but i dont use browserSync, do you have any ideas?

**Comment by EnginKARATAS** [comment]
I can`t figure out

**Comment by Anikesh-kumar** [comment]
> Problem solved. The related problem has to do with some conflicts with browsersync, as reported in [this github's issue](https://github.com/BrowserSync/browser-sync/issues/223)

hello please tell me what is exactly you did, because i am facing same issue//
