### ISSUE TITLE
How to stop an IO?

### ISSUE THREAD

**Issue by xiaodongliang** [invisibleroads/socketIO-client#110]
Hi experts,

It works well to start the socket IO by this repository. Thanks. 

but I did not find the method to stop it. In repository of Socket.io of Javascript, there is a method 'off', however python has only 'on'.

Could you shed a light?

**Comment by remaininlight** [comment]
Looks like this is hopefully waiting to be merged #94

**Comment by xiaodongliang** [comment]
@remaininlight  Sorry I was not be able to get back soon. Thank you for pointing out! I will give it a try!

**Comment by invisibleroads** [comment]
Fixed in bcd6ebae7bd6e493be159dc007c2d620f886fdcd thanks to @stafyniaksacha #94
