### ISSUE TITLE
Simple client never leaves __init__

### ISSUE THREAD

**Issue by ocschwar** [invisibleroads/socketIO-client#116]
I have a client that tries to connect, emit one message, and wait for another. Inserting code below.

The SocketIO initializer never exits, and the handlers never get run, even though server side (Flask-SocketIO) does send messages. 

`import sys
from socketIO_client import SocketIO, LoggingNamespace
import time
import requests
import websocket,ssl
import json
from argparse import ArgumentParser
import logging.handlers
logging.getLogger('requests').setLevel(logging.DEBUG)
logging.getLogger('thread').setLevel(logging.DEBUG)
logging.basicConfig(level=logging.DEBUG)

usage = """
"""

def main(args):
    def callback(*args):
        print("CB",args)

```
def on_project(*args):
    print("PROJ",args)

def on_response(*args):
    print("RESP",args)

def on_error(*args):
    print("ERROR",args)


parser = ArgumentParser( usage=usage, )
parser.add_argument( "--password",
                   action="store",
                   dest="password",
                   help="Use this password" )
parser.add_argument( "--port",
                   action="store",type=int,
                   dest="port", default=5000,
                   help="Specify port number for SSL service. " )
parser.add_argument( "--wait",
                   action="store",type=int,
                   dest="wait", default=None,
                   help="waiting " )
parser.add_argument( "project",
                   action="store",type=int,
                   default=1,
                   help="project ID. " )
parser.add_argument( "--base-url",default='https://localhost',
                   action="store",
                   dest="baseurl",
                   help="baseurl" )
parser.add_argument( "--username",
                   action="store",
                   dest="username",
                   help="Use this password" )
opts = parser.parse_args()
r = requests.get('%s:%s/project/%s'%(opts.baseurl,opts.port,opts.project), verify=False,
                 auth=requests.auth.HTTPBasicAuth(opts.username,opts.password),
                 headers={"accept":"application/json"})                     
j = json.loads(r.content.decode())
etag = r.headers['Etag']
print((etag,opts.project))
print("LOWLEVEL")
socketIO = SocketIO(opts.baseurl, opts.port)#,transports=['websocket'])
print ("INIT", socketIO._url)
logging.getLogger(socketIO._url).setLevel(logging.DEBUG)
socketIO.on('project', on_project)
print(socketIO.on('message', on_response))
socketIO.emit('project',{'id':opts.project, 'etag':etag})
print (socketIO.wait(seconds=opts.wait))
```

if **name** == '**main**':
    main(sys.argv)
`
##

**Comment by ocschwar** [comment]
Halts somewhere in 
    def _negotiate_transport(self):

**Comment by ocschwar** [comment]
It hangs waiting for a response from the client after sending the 2probe. So either my Flask server app is wrong, or my client is wrong. Time to check the socket IO standard

**Comment by ocschwar** [comment]
Flask server app DTRT with the Javascript socket.io client, so I'm leaving this ticket open for the time being. 

The Flask App is using eventlets and there is a ticket on flask-socketio saying that pings are not always handled by it.

**Comment by ocschwar** [comment]
Comparing the two clients, I notice that in the initial GET transaction, the JS client discloses its SID, while the Python client does not.

**Comment by ocschwar** [comment]
Found one issue: 

            assert response.content.lower() == b'ok'
Going to make that a pull request  for transports.py : the Flask-SocketIO gives a response in all caps.

**Comment by ocschwar** [comment]
And found another, but it belongs in python-engineio, called by flask-socketio: 

in socket.py, 

`    def _websocket_handler(self, ws):
        """Engine.IO handler for websocket transport."""

        def writer():
            while True:
                try:
                    packets = self.poll()
                except IOError:
                    break
                try:
                    for pkt in packets:
                        ws.send(pkt.encode(always_bytes=False))
                except:
                    break

        self.server.start_background_task(writer)

        if self.connected:
            # the socket was already connected, so this is an upgrade
            print (" _websocket_handler(self, ws) join:",self.queue.qsize())

            self.queue.join()  # flush the queue first
            print (" _websocket_handler(self, ws):")
`
That join() calls comes BEFORE the call to start_background_task(), which is responsible for emptying the queue. For some reason, Python client calls result in the queue already having a packet to send, while JS client calls do not.

**Comment by miguelgrinberg** [comment]
The writer task is not responsible for emptying the queue. At the time this code is executing, the client is using long-polling. The constant polls the client is doing will cause the queue to empty. The idea is that any remaining events generated from long-polling need to be processed before we switch to websocket.
