### ISSUE TITLE
How to listen to events

### ISSUE THREAD

**Issue by Johnathon332** [invisibleroads/socketIO-client#123]
Hello,

We have a node based socketio server, which is broadcasting an event, the channel name is 'pathfinder.49ee9c7a-d8cc-4374-a4ca-931b1275d621' and the even name is 'App\Events\Pathfinder\PathfinderGreet'.  How would I then listen to this using your client?

Thanks.
##

**Comment by olivia3007** [comment]
Hello,
I would like to recover the data for you to use but after I had a problem

**Comment by invisibleroads** [comment]
You are welcome to schedule a call if you still need support on this issue: https://calendly.com/crosscompute/30min
