### ISSUE TITLE
connected event?

### ISSUE THREAD

**Issue by uniquegodwin** [invisibleroads/socketIO-client#127]
Is there a connected/disconnected event in this library? I couldn't find it in your documentation with example...

I saw the     def on_connect(self):
        print('[Connected]') on your documentation. It doesn't display whenever the client gets connected.

How do I use a callback when the client gets **_reconnected_**?

I would appreciate a reconnected event / atleast a connected event that works whenever it reconnects.

Thanks.

**Comment by mathrb** [comment]
+1, also looking for a reconnect event, or connect event when client reconnects

**Comment by mathrb** [comment]
Using the LoggingSocketIONamespace, you can override the on_reconnect

**Comment by invisibleroads** [comment]
@mathrb is correct, you can use the on_reconnect event in the namespace or define the callback directly using socket.on('reconnect', on_reconnect).

@uniquegodwin We updated the documentation in a7efb7fd58c3e71873d05972d4e2f1a55af92663 to include `on_disconnect` and `on_reconnect`.

Please see #107 for details.
