### ISSUE TITLE
Handle timeouts.

### ISSUE THREAD

**Issue by jonathanslenders** [invisibleroads/socketIO-client#128]
How can we properly handle a timeout during the creation of a `SocketIO` object?

I noticed that in `logs/_yield_elapsed_time.py`, there is a "seconds" parameter, but this is not passed during the creation of a `SocketIO` object.
In our case, if we try to connect to a URL and the server is down or does not respond, the code will hang forever. Is it possible to add a timeout option here?

Thanks,
Jonathan
##

**Comment by invisibleroads** [comment]
Hmm, that's an interesting idea.

You could try using `SocketIO('localhost', wait_for_connection=False)` and catch the `ConnectionError`.

    from requests.exceptions import ConnectionError
    from socketIO_client import SocketIO
    
    try:
        socket = SocketIO(host, wait_for_connection=False)
        socket.wait()
    except ConnectionError:
        print_error('The server is down. Try again later.')

Please reopen this issue if this workaround doesn't work for you.
