### ISSUE TITLE
data recovery problem

### ISSUE THREAD

**Issue by olivia3007** [invisibleroads/socketIO-client#131]
Hello,
I would like to recover the data for you to use but after I had a problem <type 'NoneType'>
from socketIO_client import SocketIO

def on_response(*args):
    print args
  
   socketIO = SocketIO('localhost', 9000)
a =socketIO.on('connected', on_response)
print type(a)

**Comment by invisibleroads** [comment]
`socketIO.on` returns None.

You probably want to do something like this

    from socketIO_client import SocketIO

    def on_response(*args):
        print(args)

    socketIO = SocketIO('localhost', 9000)
    socketIO.on('connected', on_response)
    socketIO.wait(seconds=1)
