### ISSUE TITLE
class EngineIONamespace on_pong method

### ISSUE THREAD

**Issue by iddq** [invisibleroads/socketIO-client#133]
the comment says

        """Called after engine.io sends a pong packet.
        You can override this method."""

I think it called after engine.io _receives_ a pong packet

Am I right?

**Comment by invisibleroads** [comment]
Yes, ping and pong are events used to implement a heartbeat in the socket.io protocol.

If your client sends a ping packet, then the server is supposed to send a pong packet and the client will trigger on_pong when it receives the pong packet.

**Comment by iddq** [comment]
yes, I would like to say the comment is wrong in the source code.

**Comment by invisibleroads** [comment]
Oh whoops.
Heh, yes you are right.
