### ISSUE TITLE
Sub dependency updated and pip install fails!

### ISSUE THREAD

**Issue by kristjanmik** [invisibleroads/socketIO-client#137]
websocket-client was updated to version 0.39.0 this morning and pip install is failing now. Can we hardcode the websocket-client dependency to 0.37.0 until it is resolved? I will submit a pull request when I get back to my computer if no one else has.

**Comment by wilsonge** [comment]
The message comes from https://github.com/feus4177/socketIO-client-2/blob/master/socketIO_client/transports.py#L17 

However running this line with the import from CLI works just fine. Unfortunately didn't have time to debug further :(

**Comment by invisibleroads** [comment]
Fixed in 6d881f4396e17cabde093f3ebd8d327cae7c2ebb
