### ISSUE TITLE
incompatible websocket library is conflicting

### ISSUE THREAD

**Issue by DaniyalGeek** [invisibleroads/socketIO-client#140]
i got below errror but none command is working.

An incompatible websocket library is conflicting with the one we need.
You can remove the incompatible library and install the correct one
by running the following commands:

yes | pip uninstall websocket websocket-client
pip install -U websocket-client

After running command none of one is working?

**Comment by mattdodge** [comment]
Seeing the same thing when using websocket-client version 0.39.0 (released a few days ago). To temporarily fix, try running:
```
pip install websocket-client==0.37.0
```

This is probably still an issue though, this library might need to be updated to work with the latest `websocket-client` library.

**Comment by invisibleroads** [comment]
Fixed in 6d881f4396e17cabde093f3ebd8d327cae7c2ebb
