### ISSUE TITLE
when connect to server，raise StopIteration

### ISSUE THREAD

**Issue by AmazingRaise** [invisibleroads/socketIO-client#170]
when connect to server, I got return

97:0{"sid":"cHjXNrXgO3JKL2rgAAAz","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":60000}

however , socketIO-client raise StopIteration Exception.
I review the code , found funciton _read_packet_length in parsers.py, using ASCII to measure the length. That's the problem, I suppose.

**Comment by AmazingRaise** [comment]
def _read_packet_length(content, content_index):
    if 'sid' not in content:
        raise IndexError

    val = re.findall('([\d]+)[:][\d]', content)
    if val:
        content_index = len(val[0]) + 1
        return content_index, int(val[0])

    while get_byte(content, content_index) != 0:
        content_index += 1
    content_index += 1
    packet_length_string = ''
    byte = get_byte(content, content_index)
    while byte != 255:
        packet_length_string += str(byte)
        content_index += 1
        byte = get_byte(content, content_index)
    return content_index, int(packet_length_string)


It works, but I don't know what where happen

**Comment by AmazingRaise** [comment]
I found on server, the socekt.io version is 2.0.x, I think I should found the difference

**Comment by AmazingRaise** [comment]
https://github.com/socketio/socket.io/pull/2833
socket.io(version 2.0.x ):Merge Engine.IO and Socket.IO handshake packets; so read the packet error.Need do something to void this

**Comment by juesato** [comment]
Likely relevant: https://github.com/invisibleroads/socketIO-client/issues/159

**Comment by AmazingRaise** [comment]
https://github.com/nexus-devs/socketIO-client-2.0.3,  have solve the problem
