### ISSUE TITLE
Not an issue, just a question about threading

### ISSUE THREAD

**Issue by simonmorley** [invisibleroads/socketIO-client#22]
Great library, really helped us out. Moreover, it's eased our transition from Ruby to Python :)

We ran into a problem with the fact it's using threading to 'process' the messages returned from the server. Because of the embedded devices we're running this on right now, the memory usage has hit the ceiling at a min. of 39%. Yeah, sounds high but we're working with 32mb!

So, we looked writing something in c++ but that's a no go right now and we'd like to push this a little further.

Do you see any way we can write this without threads or at least, reduce the usage a little?

I have a non threaded websocket client running in Python that's on about 23%. That's actually achievable, I just don't see how we'd get the messages.

Simon

**Comment by johnrickman** [comment]
Make threads great again.! 

How can I listen for events without blocking the main thread with wait()?
