### ISSUE TITLE
Client not connecting to a socket.io server

### ISSUE THREAD

**Issue by nayefc** [invisibleroads/socketIO-client#27]
I have a server running socket.io on port 80. It works perfectly fine with another client that is written using socket.io's client in Javascript. Now I am trying to write a Python client for that server using this library.

Following the instructions, here's my code:

``` python
from socketIO_client import SocketIO, BaseNamespace
class Namespace(BaseNamespace):
    def on_connect(self):
        print('Connected')

socketIO = SocketIO('http://server-url-here.com/', 80, Namespace) 
socketIO.wait(seconds=1)
```

However, I get an error: `No handlers could be found for logger "socketIO_client"` and nothing happens when the server connects and starts emitting.

Am I missing something here? I also tried including the /socket.io/1 to the URL but that did not work either.

Thanks,

**Comment by felipe010203** [comment]
try this:
 
*in env_s40.py
class S40YowsupEnv(YowsupEnv):
    _VERSION = "2.16.11"
    _OS_NAME= "S40"
    _OS_VERSION = "14.26"
    _DEVICE_NAME = "302"
    _MANUFACTURER = "Nokia"
    _TOKEN_STRING  = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1478194306452{phone}"
    _AXOLOTL = True

* sudo python yowsup-cli registration --requestcode sms --phone 57346789234 --cc 57 --mcc 732 --mnc 101 -E android

 sudo yowsup-cli registration --register 149210 --phone 57346789234 --cc 57

*in env.py
DEFAULT="Android"
