### ISSUE TITLE
Don't Reconnect to Blank Namespace Unconditionally

### ISSUE THREAD

**Issue by bradjc** [invisibleroads/socketIO-client#40]
I've noticed that if the socket.io connection is disconnected and then reconnects, the client connects to the blank namespace (`path==''`), even if that wasn't specified as a namespace at the beginning. The reason is this line:

    class SocketIO(object):
        def __init__(
             ...
             self.define(Namespace)

in the constructor. Adding that namespace adds it to the list of namespaces, and therefore causes it to be connected when the socket.io connection is reestablished. The default blank namespace should be changed so this default connection doesn't happen.

**Comment by invisibleroads** [comment]
Thanks for highlighting this bit.
