### ISSUE TITLE
stream=True for xhr-polling transport

### ISSUE THREAD

**Issue by vishalwy** [invisibleroads/socketIO-client#45]
I was missing a lot of events from the server. Setting stream=True for the session solved it.

**Comment by invisibleroads** [comment]
Hi Vishal, I'm unable to recreate a situation where the xhr-polling transport misses events from the server.  Can you please provide more details?

Adding stream=True to _XHR_PollingTransport.recv() didn't seem to affect any unit tests, so I will include your suggestion for now.
