### ISSUE TITLE
Emit at variable rate but still detect disconnections

### ISSUE THREAD

**Issue by mattdodge** [invisibleroads/socketIO-client#50]
This may be an issue, but it may also just be a question.

How would one emit to a socket at a variable rate (i.e. based on user input or something similar) but still use `wait` to handle disconnections and reconnections? When the socket is waiting, it cannot emit anything, but if you don't wait, you don't capture the heartbeats and disconnections. Am I missing something?

**Comment by invisibleroads** [comment]
The ideal solution is to handle heartbeats and events in separate processes.

For now, I think some people use a loop with a short wait interval.

```
while True:
    if check_flag():
        socketIO.emit('whee')
    socketIO.wait(0.1)
```
