### ISSUE TITLE
Client (master) does not reconnect after server failure

### ISSUE THREAD

**Issue by valhallasw** [invisibleroads/socketIO-client#63]
This is somewhat related to #53, but slightly different; #53 relates to the version on PyPI, which /does/ reconnect to the server, but which doesn't do a new namespace handshake. With master, this is what happens:

```
WARNING:socketIO_client:[connection error] connection closed ()
WARNING:socketIO_client:stream.wikimedia.org:80/socket.io/1: [connection error] connection closed ()
DEBUG:socketIO_client:ws://stream.wikimedia.org:80/socket.io/1/websocket/456634781549:  [disconnect]
```

and the client does not automatically reconnect. Is this something I'm supposed to handle manually (e.g. with on_disconnect), or is this a bug?

**Comment by invisibleroads** [comment]
Thanks!
