### ISSUE TITLE
heartbeats not sent if wait time is too small

### ISSUE THREAD

**Issue by valhallasw** [invisibleroads/socketIO-client#64]
If the calling process uses a loop such as

```
        while self.running:
            self.client.wait(seconds=0.1)
            ...
```

no heartbeats are sent, as for each consecutive wait() call, a _new_  timer is instantiated ( https://github.com/invisibleroads/socketIO-client/blob/master/socketIO_client/__init__.py#L194 ), and thus the heartbeat_pacemaker gets passed 'zero' as time instead of the time the client has been connected.

**Comment by invisibleroads** [comment]
Fixed thanks to https://github.com/invisibleroads/socketIO-client/pull/38

47b5f2dd69714c438a93f675ed3587014d2fbf8f
