### ISSUE TITLE
PEP 440 package naming & versioning

### ISSUE THREAD

**Issue by jayvdb** [invisibleroads/socketIO-client#66]
builds using this package report a warning for every release, including 0.5.3

PEP440Warning: 'socketIO (client-0.5.3)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.

See e.g.

https://travis-ci.org/jayvdb/pywikibot-core/jobs/50130757

And the same issue raised with websocket-client
https://github.com/liris/websocket-client/issues/147

**Comment by invisibleroads** [comment]
John, thanks for reporting this warning.  The offending code seems to be in setuptools 8.2.1.
https://bitbucket.org/pypa/setuptools/issue/307/pep440-code-in-setuptools-821-is-parsing

I'm not getting this error with setuptools 12.0.5.  Please feel free to reopen the issue if I'm mistaken.

**Comment by jayvdb** [comment]
As you saw on liris/websocket-client/issues/147 , this does happen with setuptools 12.0.5 .

**Comment by invisibleroads** [comment]
I believe that you see the error message with setuptools 12.0.5.

But a fix on our part means removing the hyphen in the package name.  There are a lot of packages with hyphens in their name, so I am hoping that setuptools will fix the issue on their side instead.

**Comment by jayvdb** [comment]
I share your hope that setuptools might improve their algorithm, but this is just a hope, especially as PEP 440 is quite clear about this.
What is the impact of changing the package name to socketIO_client ?  According to PEP 426, hyphen and underscore must be treated identically.

**Comment by jayvdb** [comment]
Note that 0.6.1 does not emit this warning, but the older versions in pypi still cause this warning.
https://travis-ci.org/wikimedia/pywikibot-core/jobs/53629395
Fully appreciate that modifying older releases is not a good idea, and setuptools should *really* not emit warnings when it does find the canonical name of the package containing a '_' as it should then be able to recognise all prior versions using '-' are *the same name*.  This appears to be the bug at https://bitbucket.org/pypa/setuptools/issue/325/unnecessary-pep440-warnings-in

Another related bug is
https://bitbucket.org/pypa/setuptools/issue/351/pep440-warnings-emitted-for-valid-versions

**Comment by invisibleroads** [comment]
Thanks for the note.  Unfortunately, I will not modify older releases.  

Really, this is an issue that the setuptools maintainers need to fix and I think you should bring your case to them.
