### ISSUE TITLE
Add rooms

### ISSUE THREAD

**Issue by invisibleroads** [invisibleroads/socketIO-client#72]

**Comment by ergofobe** [comment]
Aren't rooms a server-side thing? From what I know of the Javascript implementation of socket.io-client, the client is oblivious to what rooms it's joined to (other than having to emit a 'join' or 'subscribe' message instructing the server to join it to a room). There's no mechanism for emitting to a specific room in the javascript socket.io-client as far as I know. That's done through namespaces presumably.

**Comment by invisibleroads** [comment]
Thank you for this information!  To be honest, I haven't looked into it yet.  Someone asked for room support and I just put this reminder here to see how people actually need it.  If, as you say, room support is purely server-side, then that is good news.

**Comment by gonzoramos** [comment]
http://socket.io/docs/rooms-and-namespaces/

one should be able to "emit" to a room like so:

> io.to('some room').emit('some event'):

so all that is needed on the client library is access to the "to" function

**Comment by invisibleroads** [comment]
@gonzoramos

After thinking about this a bit and searching through the [official socket.io-client repository](https://github.com/socketio/socket.io-client.git), @ergofobe is right, rooms are purely server-side, which includes the ability to use the commands socket.join, socket.leave, io.to, io.in.

The [documentation](http://socket.io/docs/rooms-and-namespaces/) hints at this by using the event "connection" which is a default event only on the server.

Thus we don't need to implement anything to support rooms in the client.
