### ISSUE TITLE
Version >0.5.5 not working with gevent-socketio

### ISSUE THREAD

**Issue by Nabla128k** [invisibleroads/socketIO-client#74]
Just found, that while version >0.5.5 implements SocketIO protocol version 1.x, it won't work with gevent-socketio server. That's not the socketIO-client's fault, but it takes me quite a lot of time to realize this, so, maybe it can be useful for someone else.

**Comment by invisibleroads** [comment]
Thanks for the suggestion!  I put a note in the README advising people to use 0.5.5 for gevent-socketio.
