### ISSUE TITLE
How to create a pub/sub client? [$15]

### ISSUE THREAD

**Issue by F483** [invisibleroads/socketIO-client#76]
I've been trying to implement the python equivalent of the code below but cannot seem to get it working.

    var io = require('socket.io-client')
    var socket = io('http://devel.hz.udoidio.info:5000')

    socket.on('connect', function () {
      socket.emit('subscribe', 'new-tx')
    })

    socket.on('new-tx', function (txid) {
      console.log('New tx: ' + txid)
    })

I tried this approach but it does not seem to yield anything.

    from socketIO_client import SocketIO, LoggingNamespace
    
    def on_response(*args):
        print 'on_response', args

    baseurl = "http://v1.livenet.bitcoin.chromanode.net"
    socketIO = SocketIO(baseurl, 80, LoggingNamespace)
    socketIO.on('subscribe', on_response)
    socketIO.emit('subscribe', 'new-block')
    socketIO.wait()

**Comment by F483** [comment]
I figured it out myself.

    from socketIO_client import SocketIO

    def on_response(*args):
        print 'on_response', args

    baseurl = "http://devel.hz.udoidio.info"
    with SocketIO(baseurl, 5000) as socketIO:
        socketIO.on('new-tx', on_response)
        socketIO.emit('subscribe', 'new-tx')
        socketIO.wait()

**Comment by invisibleroads** [comment]
Good!  It looks like you just had a typo.
