### ISSUE TITLE
Improve object cleanup when connection fails

### ISSUE THREAD

**Issue by mattporritt** [invisibleroads/socketIO-client#77]
When wrapping a socket connection in a try, so an exception can be caught if the connection can't be made because the socket server is unreachable, e.g.
try:
    ws = SocketIO('localhost', 8080, wait_for_connection=False)
except:
    handle_exception()

An uncaught exception occurs: 
Exception ignored in: bound method SocketIO.__del__ of <socketIO_client.SocketIO object at 0x7f9be435efd0

This is because errors raised by __del__ output to stderr and are not caught.
The cause of this looks to be in _close() when halt() is called on _heartbeat_thread This is because there is no _heartbeat_thread for the object as an exception occurred during initialization. 

A suggested solution is to wrap the halt() call in a try block, e.g.
        try:
            self._heartbeat_thread.halt()
        except:
            pass

I haven't made a pull request with this as the solution as the author may not want this behavior, so I wanted to check first

**Comment by invisibleroads** [comment]
Thanks!
