### ISSUE TITLE
Backport for requests 0.8.2?

### ISSUE THREAD

**Issue by scfc** [invisibleroads/socketIO-client#79]
I want to backport socketIO_client 0.5.3 from Ubuntu Utopic to Precise (cf. https://bugs.launchpad.net/precise-backports/+bug/1458651).  Ubuntu Precise ships requests 0.8.2 which makes my test script (from https://wikitech.wikimedia.org/wiki/RCStream#Python):

```python
import socketIO_client

class WikiNamespace(socketIO_client.BaseNamespace):
    def on_change(self, change):
        print('%(user)s edited %(title)s' % change)

    def on_connect(self):
        self.emit('subscribe', 'commons.wikimedia.org')


socketIO = socketIO_client.SocketIO('stream.wikimedia.org', 80)
socketIO.define(WikiNamespace, '/rc')

socketIO.wait()
```

fail with:

```
scfc@toolsbeta-test-precise:~$ bin/socketio_client-test.py 
Traceback (most recent call last):
  File "bin/socketio_client-test.py", line 13, in <module>
    socketIO = socketIO_client.SocketIO('stream.wikimedia.org', 80)
  File "/usr/lib/python2.7/dist-packages/socketIO_client/__init__.py", line 136, in __init__
    self.define(Namespace)
  File "/usr/lib/python2.7/dist-packages/socketIO_client/__init__.py", line 150, in define
    namespace = Namespace(self._transport, path)
  File "/usr/lib/python2.7/dist-packages/socketIO_client/__init__.py", line 237, in _transport
    self.__transport = self._get_transport()
  File "/usr/lib/python2.7/dist-packages/socketIO_client/__init__.py", line 251, in _get_transport
    self.is_secure, self.base_url, **self.kw)
  File "/usr/lib/python2.7/dist-packages/socketIO_client/__init__.py", line 402, in _get_socketIO_session
    response_parts = response.text.split(':')
AttributeError: 'Response' object has no attribute 'text'
Exception AttributeError: "'SocketIO' object has no attribute '_SocketIO__transport'" in <bound method SocketIO.__del__ of <socketIO_client.SocketIO object at 0x1723310>> ignored
scfc@toolsbeta-test-precise:~$
```

To fix this, I replaced the references to `response.text` in `__init__.py` and `transports.py` with `response.content` (cf. e2d9242b4436dbb7b1f1d085d64f548162074ae7).  With that, my test script succeeds, but I'm lacking the insight if this is a universal solution or only works for my specific test case.

So before I proceed with pushing this to Ubuntu Precise, I'd like to solicit some input/test cases/confirmation/etc. if this is a reasonable fix.

**Comment by invisibleroads** [comment]
Does response.content exist in the latest version of requests?
Why do you not want to update requests to the latest version?

**Comment by scfc** [comment]
With regard to motivation, in our cluster ([Wikimedia Tools](https://wikitech.wikimedia.org/wiki/Nova_Resource:Tools)) a homebrewed backport of requests 2.0.0 is installed on Precise instances (and it does offer `response.content`, but see below).  However, my backport of socketIO_client is intended for the "general audience", i. e. all Precise instances in existence.  Requiring them to update to requests 2.0.0 to install socketIO_client is not an option because too many things could break (described in many more words at https://wiki.ubuntu.com/StableReleaseUpdates).  So I need to make socketIO_client compatible with requests 0.8.2 because that is what will be available.

I have revised my patch, though.  While previously I always used `response.content`, I now use it only if `response.text` is not available à la:

```python
-    response_parts = response.text.split(':')
+    try:
+        response_text = response.text
+    except AttributeError:
+        response_text = response.content
+    response_parts = response_text.split(':')
```

This works with requests 0.8.2 as shipped with Precise and with our 2.0.0 backport.

What I don't know is if the success of my test script is indicative of a universally working solution or `stream.wikimedia.org` is just too "plain" so that there are no differences between `response.text` and `response.content` with that particular server.  I mean "universally working" here with a grain of salt: If some edge cases do not work, that's okay, but with my backport a user on a Precise machine should be able to successfully work with other servers besides `stream.wikimedia.org` :-).

**Comment by invisibleroads** [comment]
It appears you are working with an earlier version of socketIO-client that only supports socket.io protocol 0.9.

I'm also assuming that you do not want to use virtualenv to keep a local requests 2.7.0 separate from the global requests 0.8.2.

- In requests 0.8.2, response.content is decoded data (see below)
- In requests 2.7.0, response.content is raw data and response.text is decoded data (see below)

This tells me that the version of your patch that uses exceptions should work, because it correctly uses the decoded data in both cases.

**requests 0.8.2**

    @property
    def content(self):
        """Content of the response, in bytes or unicode
        (if available).
        """

        if self._content is None:
            # Read the contents.
            try:
                if self._content_consumed:
                    raise RuntimeError(
                        'The content for this response was already consumed')

                self._content = self.raw.read()
            except AttributeError:
                self._content = None

        content = self._content

        # Decode GZip'd content.
        if 'gzip' in self.headers.get('content-encoding', ''):
            try:
                content = decode_gzip(self._content)
            except zlib.error:
                pass

        # Decode unicode content.
        if self.config.get('decode_unicode'):

            # Try charset from content-type

            if self.encoding:
                try:
                    content = unicode(content, self.encoding)
                except UnicodeError:
                    pass

            # Fall back:
            try:
                content = unicode(content, self.encoding, errors='replace')
            except TypeError:
                pass

        self._content_consumed = True
        return content

**requests 2.7.0**

    @property
    def content(self):
        """Content of the response, in bytes."""
    
        if self._content is False:
            # Read the contents.
            try:
                if self._content_consumed:
                    raise RuntimeError(
                        'The content for this response was already consumed')

                if self.status_code == 0:
                    self._content = None
                else:
                    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()

            except AttributeError:
                self._content = None

        self._content_consumed = True
        # don't need to release the connection; that's been handled by urllib3
        # since we exhausted the data.
        return self._content

    def text(self):
        """Content of the response, in unicode.

        If Response.encoding is None, encoding will be guessed using
        ``chardet``.
        
        The encoding of the response content is determined based solely on HTTP
        headers, following RFC 2616 to the letter. If you can take advantage of
        non-HTTP knowledge to make a better guess at the encoding, you should
        set ``r.encoding`` appropriately before accessing this property.
        """

        # Try charset from content-type
        content = None
        encoding = self.encoding

        if not self.content:
            return str('')

        # Fallback to auto-detected encoding.
        if self.encoding is None:
            encoding = self.apparent_encoding

        # Decode unicode from given encoding.
        try:
            content = str(self.content, encoding, errors='replace')
        except (LookupError, TypeError):
            # A LookupError is raised if the encoding was not found which could
            # indicate a misspelling or similar mistake.
            #
            # A TypeError can be raised if encoding is None
            #
            # So we try blindly encoding.
            content = str(self.content, errors='replace')

        return content

    @property
    def apparent_encoding(self):
        """The apparent encoding, provided by the chardet library"""
        return chardet.detect(self.content)['encoding']

**Comment by scfc** [comment]
Thank you very much for the detailed explanation!  That was very helpful.
