### ISSUE TITLE
Python 3 support for socketIO-client 0.5.6 

### ISSUE THREAD

**Issue by shubhamd** [invisibleroads/socketIO-client#83]
As mentioned on PyPi page [here](https://pypi.python.org/pypi/socketIO-client), socketIO-client supports Python 3.4 since version `0.5.5`. but when I tried to run a simple example with Python 3.4, It showed following error when `socketIO.wait()` method was called. 
![error](https://cloud.githubusercontent.com/assets/3493763/8187921/55a4f5c2-1470-11e5-8612-87c1f4871adc.png)
##

**Comment by invisibleroads** [comment]
There are some new versions now.
https://pypi.python.org/pypi/socketIO-client/0.5.7.2 (for socket.io protocol 0.9)
https://pypi.python.org/pypi/socketIO-client/0.7.2 (for socket.io protocol 1.x)

Please feel free to reopen this issue if the new versions don't work with your configuration.

**Comment by haridask** [comment]
pip3 install socketio-client==0.5.7.2 gives the following error 

Collecting socketio-client==0.5.7.2
  Downloading https://files.pythonhosted.org/packages/79/30/69dd00555bd877877b5ffba2dcd5d028242303f84fd6ffa70ad944d7dfe9/socketIO-client-0.5.7.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-jwr4mfzp/socketio-client/setup.py", line 6, in <module>
        README = open(os.path.join(here, 'README.rst')).read()
      File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 5782: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-jwr4mfzp/socketio-client/
