### ISSUE TITLE
Unable to handle invalid namespace

### ISSUE THREAD

**Issue by softforge** [invisibleroads/socketIO-client#84]
We have the occasional timing issue where the python client attempts to connect to a namespace before it has been created (from an action of another client). The SocketIO server logs the following:

    socket.io:server incoming connection with id WvR6SwDvKMssDHf2AUFD
    socket.io:client connecting to namespace /
    socket.io:namespace adding socket to nsp /
    socket.io:socket socket connected - writing packet
    socket.io:socket joining room WvR6SwDvKMssDHf2AUFD
    socket.io:client writing packet {"type":0,"nsp":"/"}
    socket.io-parser encoding packet {"type":0,"nsp":"/"}
    socket.io-parser encoded {"type":0,"nsp":"/"} as 0
    socket.io:socket joined room WvR6SwDvKMssDHf2AUFD
    socket.io-parser decoded 0/custom-namespace, as {"type":0,"nsp":"/custom-namespace"}
    socket.io:client connecting to namespace /custom-namespace
    socket.io:client writing packet {"type":4,"nsp":"/custom-namespace","data":"Invalid namespace"}
    socket.io-parser encoding packet {"type":4,"nsp":"/custom-namespace","data":"Invalid namespace"}
    socket.io-parser encoded {"type":4,"nsp":"/custom-namespace","data":"Invalid namespace"} as 4/custom-namespace,"Invalid namespace"

However, this appears to cause the python client to hang. I have wrapped the connection in a try but it hasn't helped. I cannot see any code to deal with invalid namespaces and cant work out how to handle it in my code.

What is the best way to deal with connecting to an invalid namespace?

Many thanks

**Comment by dom-f** [comment]
This only occurs when using BaseNamespace.  If using LoggingNamespace then an exception is thrown within on_error which can at least be caught though the exception is actually a bad call to on_error().

    Traceback (most recent call last):
      File "/home/dom/code/research/DomF/tmp/namespaces.py", line 10, in <module>
        dom3_namespace = socketIO.define(LoggingNamespace, '/dom3') #
      File "/usr/local/lib/python2.7/dist-packages/socketIO_client/__init__.py", line 356, in define
    self.wait(for_connect=True)
      File "/usr/local/lib/python2.7/dist-packages/socketIO_client/__init__.py", line 229, in wait
        self._process_packets()
      File "/usr/local/lib/python2.7/dist-packages/socketIO_client/__init__.py", line 253, in _process_packets
        self._process_packet(engineIO_packet)
      File "/usr/local/lib/python2.7/dist-packages/socketIO_client/__init__.py", line 458, in _process_packet
    delegate(socketIO_packet_data, namespace)
      File "/usr/local/lib/python2.7/dist-packages/socketIO_client/__init__.py", line 490, in _on_error
    namespace._find_packet_callback('error')(data)
      File "/usr/local/lib/python2.7/dist-packages/socketIO_client/namespaces.py", line 210, in on_error
    super(LoggingSocketIONamespace, self).on_error()
    TypeError: on_error() takes exactly 2 arguments (1 given)


If using BaseNamespace then the hang occurs whilst waiting for connection in the code below within the SockerIO class.

    def define(self, Namespace, path=''):
        self._namespace_by_path[path] = namespace = Namespace(self, path)
        if path:
            self.connect(path)
            self.wait(for_connect=True)
        return namespace



The issue can be reproduced with the code below.

    from socketIO_client import SocketIO, BaseNamespace

    socketIO = SocketIO('https://127.0.0.1, 14000, verify=True)

    dom3_namespace = socketIO.define(BaseNamespace, '/dom3') # This name space does not exist and hang occurs here
    dom3_namespace.emit('aaa')
    socketIO.wait(seconds=3)

**Comment by invisibleroads** [comment]
Now, trying to define a namespace that does not exist on the server will raise a ConnectionError. Thank you for reporting this issue.

**Comment by invisibleroads** [comment]
Thanks to @wilsonge for suggesting the fix in https://github.com/feus4177/socketIO-client-2/pull/4/commits/9569e14b45c190cdf1a098813214cc6158744010
