### ISSUE TITLE
testsuite, how to run

### ISSUE THREAD

**Issue by idella** [invisibleroads/socketIO-client#90]
Taking the last release -0.5.6 released the same day as -0.6.5
1. on running it it objects to the local import structure in the __init__.py
(from .. import SocketIO, LoggingNamespace, find_callback)
which might work once installed.
2. On changing that to an abs path:

1. It complete running with
```bash
python socketIO_client /tests/__init__.py
```
with nil output to the screen

2. Using 
```bash
nosetests socketIO_client /tests/__init__.py 
```
 it then simply hangs.

Is it a normal testsuite?  When there is no output to tty it generally means the tests were no actually run. They require the output to confirm that something actually happened. This just leaves total doubt

**Comment by invisibleroads** [comment]
@idella These test suites assume that the test socket.io server is running (please see https://github.com/invisibleroads/socketIO-client/blob/master/.travis.yml).

You can launch the test socket.io server in another terminal with the following command:
```DEBUG=* node socketIO_client/tests/serve.js```
