### ISSUE TITLE
Dependency on "requests" is too liberal

### ISSUE THREAD

**Issue by danielquinn** [invisibleroads/socketIO-client#92]
It appears that `Session` objects in the `requests` library haven't always had a `prepare_request` method, and if you have an older version of requests (I was on 1.2.3), websocket transports will silently fallback to `xhr-polling`.

So there appear to be problems in two places: (a) `setup.py` allows for installations of `requests` that are incapable of doing the stuff this library expects of it, and (b) `EngineIO._negotiate_transport()` is suppressing the error to everyone with:

```python
try:
    ...
except Exception:
    pass
```

That `pass` suppressed an exception that looked like this:

    AttributeError: 'Session' object has no attribute 'prepare_request'

The solution for me was just to upgrade requests to the latest version (2.7.0 at the moment) and then websockets worked without issue.

**Comment by invisibleroads** [comment]
Fixed in https://github.com/invisibleroads/socketIO-client/commit/67bb9f66afd692ed08834c807450a5cc9cc419d0

Thanks!
