### ISSUE TITLE
Backport README encoding to 0.5.6

### ISSUE THREAD

**Issue by xZise** [invisibleroads/socketIO-client#95]
Hi, is it possible to backport 12fa6c52 onto the 0.5.6 branch. The Wikimedia's streams unfortunately still use 0.9 so we can't upgrade to a newer version and one of our users had yesterday the problem that the default encoding was not UTF-8 which would be fixed by the mentioned patch.

Now unfortunately it depends on cd92f1c0 which shouldn't be backported probably. But anyway if you want I can also provide a pull request.
##

**Comment by invisibleroads** [comment]
Whoops, just saw this. Please reopen this issue if you need the change to be deployed to PyPI.

For now, the fix is in d9f4293897e7c1e75966d11bc9d12a3fc5fed7f9
