### ISSUE TITLE
Disconnection - Question

### ISSUE THREAD

**Issue by KKKSzili** [invisibleroads/socketIO-client#98]
Disconnection works well, if i restart the server, but if i try to unplug the network cable, i do not get any disconnect from client side. I wan't to detect when the connection dropped at home. (Ex. Internet provider disconnects).

Setup: 
- Node server on VPS
- Python3.5  socketIO-client on a RaspberryPi
- Websockets transport
- Using socketIO.wait()
- Same issue on ws or wss

Waiting for a response,
Szilard
##

**Comment by invisibleroads** [comment]
Fixed in 4f7c959 by #136 thanks to @astrikos
